-file("/usr/local/Cellar/erlang/23.3.1/lib/erlang/lib/parsetools-2.2/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(asm_lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("./priv/asm_lexer.xrl", 137).

id_validate(Chars, Line) ->
  case length(Chars) > 40 of
    true ->
      io:format("WARNING: Identifier too long. ~w: ~s -> ~s~n", [Line, Chars, lists:sublist(Chars, 40)]),
      lists:sublist(Chars, 40);
    _Else ->
      Chars
  end.

int_validate(Chars, _Line) -> int_validate_del_zero(Chars).
int_validate_del_zero([$0] = Chars) -> Chars;
int_validate_del_zero([$0|Chars]) -> int_validate_del_zero(Chars);
int_validate_del_zero(Chars) -> Chars.

intwr_validate(Chars, Line) ->
  io:format("WARNING: A hexadecimal literal hasn't a trailing H. ~w: ~s -> ~s~n", [Line, Chars, Chars ++ "H"]),
  int_validate(Chars ++ "H", Line).

str_validate(Chars, _Line) -> Chars.

-file("/usr/local/Cellar/erlang/23.3.1/lib/erlang/lib/parsetools-2.2/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,Tlen,_Ics1,L1,_S1} ->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            string_cont(Tcs1, L2, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            token_cont(Tcs1, L2, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            tokens_cont(Tcs1, L2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

-compile({nowarn_unused_function, [yyrev/1, yyrev/2, yypre/2, yysuf/2]}).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

-compile({nowarn_unused_function, adjust_line/4}).

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("./priv/asm_lexer.erl", 327).
yystate() -> 109.

yystate(112, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line};
yystate(111, [32|Ics], Line, Tlen, _, _) ->
    yystate(111, Ics, Line, Tlen+1, 2, Tlen);
yystate(111, [9|Ics], Line, Tlen, _, _) ->
    yystate(111, Ics, Line, Tlen+1, 2, Tlen);
yystate(111, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,111};
yystate(110, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line};
yystate(109, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(105, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(97, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [113|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [107|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [106|Ics], Line, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [98|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [83|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(92, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [80|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [81|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [79|Ics], Line, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [78|Ics], Line, Tlen, Action, Alen) ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [77|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [76|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [75|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [74|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [67|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [66|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [65|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(95, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(103, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(111, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(107, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(107, Ics, Line+1, Tlen+1, Action, Alen);
yystate(109, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(111, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(83, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [C|Ics], Line, Tlen, Action, Alen) when C >= 68, C =< 70 ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [C|Ics], Line, Tlen, Action, Alen) when C >= 71, C =< 73 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [C|Ics], Line, Tlen, Action, Alen) when C >= 85, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [C|Ics], Line, Tlen, Action, Alen) when C >= 101, C =< 105 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(109, [C|Ics], Line, Tlen, Action, Alen) when C >= 115, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(109, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,109};
yystate(108, [78|Ics], Line, Tlen, Action, Alen) ->
    yystate(104, Ics, Line, Tlen+1, Action, Alen);
yystate(108, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,108};
yystate(107, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line};
yystate(106, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line};
yystate(105, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(101, Ics, Line, Tlen+1, Action, Alen);
yystate(105, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,105};
yystate(104, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line};
yystate(103, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(99, Ics, Line, Tlen+1, Action, Alen);
yystate(103, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(103, Ics, Line, Tlen+1, Action, Alen);
yystate(103, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(103, Ics, Line, Tlen+1, Action, Alen);
yystate(103, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(103, Ics, Line, Tlen+1, Action, Alen);
yystate(103, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 33 ->
    yystate(103, Ics, Line, Tlen+1, Action, Alen);
yystate(103, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 93 ->
    yystate(103, Ics, Line, Tlen+1, Action, Alen);
yystate(103, [C|Ics], Line, Tlen, Action, Alen) when C >= 95, C =< 123 ->
    yystate(103, Ics, Line, Tlen+1, Action, Alen);
yystate(103, [C|Ics], Line, Tlen, Action, Alen) when C >= 125 ->
    yystate(103, Ics, Line, Tlen+1, Action, Alen);
yystate(103, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,103};
yystate(102, [82|Ics], Line, Tlen, Action, Alen) ->
    yystate(106, Ics, Line, Tlen+1, Action, Alen);
yystate(102, [78|Ics], Line, Tlen, Action, Alen) ->
    yystate(110, Ics, Line, Tlen+1, Action, Alen);
yystate(102, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,102};
yystate(101, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(100, [78|Ics], Line, Tlen, Action, Alen) ->
    yystate(96, Ics, Line, Tlen+1, Action, Alen);
yystate(100, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,100};
yystate(99, Ics, Line, Tlen, _, _) ->
    {37,Tlen,Ics,Line};
yystate(98, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(102, Ics, Line, Tlen+1, Action, Alen);
yystate(98, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(112, Ics, Line, Tlen+1, Action, Alen);
yystate(98, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,98};
yystate(97, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(97, [45|Ics], Line, Tlen, _, _) ->
    yystate(89, Ics, Line, Tlen+1, 34, Tlen);
yystate(97, [43|Ics], Line, Tlen, _, _) ->
    yystate(81, Ics, Line, Tlen+1, 34, Tlen);
yystate(97, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(97, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(97, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(97, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,97};
yystate(96, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line};
yystate(95, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(99, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(95, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(95, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(95, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 38 ->
    yystate(95, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 93 ->
    yystate(95, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [C|Ics], Line, Tlen, Action, Alen) when C >= 95, C =< 123 ->
    yystate(95, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [C|Ics], Line, Tlen, Action, Alen) when C >= 125 ->
    yystate(95, Ics, Line, Tlen+1, Action, Alen);
yystate(95, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,95};
yystate(94, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line};
yystate(93, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(93, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(93, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(93, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(93, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,93};
yystate(92, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 21, Tlen);
yystate(92, [45|Ics], Line, Tlen, _, _) ->
    yystate(88, Ics, Line, Tlen+1, 21, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 21, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 21, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 21, Tlen);
yystate(92, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line,92};
yystate(91, [104|Ics], Line, Tlen, _, _) ->
    yystate(87, Ics, Line, Tlen+1, 36, Tlen);
yystate(91, [72|Ics], Line, Tlen, _, _) ->
    yystate(87, Ics, Line, Tlen+1, 36, Tlen);
yystate(91, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(91, Ics, Line, Tlen+1, 36, Tlen);
yystate(91, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(91, Ics, Line, Tlen+1, 36, Tlen);
yystate(91, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,91};
yystate(90, [78|Ics], Line, Tlen, Action, Alen) ->
    yystate(94, Ics, Line, Tlen+1, Action, Alen);
yystate(90, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,90};
yystate(89, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(85, Ics, Line, Tlen+1, Action, Alen);
yystate(89, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,89};
yystate(88, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Tlen+1, Action, Alen);
yystate(88, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,88};
yystate(87, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line};
yystate(86, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 13, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 13, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 13, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 13, Tlen);
yystate(86, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,86};
yystate(85, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line};
yystate(84, [80|Ics], Line, Tlen, Action, Alen) ->
    yystate(80, Ics, Line, Tlen+1, Action, Alen);
yystate(84, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,84};
yystate(83, [104|Ics], Line, Tlen, _, _) ->
    yystate(87, Ics, Line, Tlen+1, 35, Tlen);
yystate(83, [72|Ics], Line, Tlen, _, _) ->
    yystate(87, Ics, Line, Tlen+1, 35, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(83, Ics, Line, Tlen+1, 35, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(91, Ics, Line, Tlen+1, 35, Tlen);
yystate(83, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line,83};
yystate(82, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(82, [78|Ics], Line, Tlen, _, _) ->
    yystate(86, Ics, Line, Tlen+1, 34, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 77 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 79, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(82, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,82};
yystate(81, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(81, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,81};
yystate(80, [67|Ics], Line, Tlen, Action, Alen) ->
    yystate(76, Ics, Line, Tlen+1, Action, Alen);
yystate(80, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,80};
yystate(79, [115|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 0, Tlen);
yystate(79, [116|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 0, Tlen);
yystate(79, [92|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 0, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(79, Ics, Line, Tlen+1, 0, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 91 ->
    yystate(79, Ics, Line, Tlen+1, 0, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 93, C =< 114 ->
    yystate(79, Ics, Line, Tlen+1, 0, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 117 ->
    yystate(79, Ics, Line, Tlen+1, 0, Tlen);
yystate(79, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,79};
yystate(78, [100|Ics], Line, Tlen, _, _) ->
    yystate(82, Ics, Line, Tlen+1, 34, Tlen);
yystate(78, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(78, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,78};
yystate(77, Ics, Line, Tlen, _, _) ->
    {32,Tlen,Ics,Line};
yystate(76, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line};
yystate(75, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 9, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 9, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 9, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 9, Tlen);
yystate(75, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,75};
yystate(74, [110|Ics], Line, Tlen, _, _) ->
    yystate(78, Ics, Line, Tlen+1, 34, Tlen);
yystate(74, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(74, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,74};
yystate(73, [114|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 34, Tlen);
yystate(73, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(73, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,73};
yystate(72, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(72, [82|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 34, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 81 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 83, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(72, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,72};
yystate(71, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(71, [85|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 34, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 84 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 86, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(71, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,71};
yystate(70, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 14, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 14, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 14, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 14, Tlen);
yystate(70, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line,70};
yystate(69, [103|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 34, Tlen);
yystate(69, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 104, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(69, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,69};
yystate(68, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(68, [71|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 34, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 72, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(68, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,68};
yystate(67, [104|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(67, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(67, [76|Ics], Line, Tlen, _, _) ->
    yystate(71, Ics, Line, Tlen+1, 34, Tlen);
yystate(67, [72|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(67, [71|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(63, Ics, Line, Tlen+1, 34, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(63, Ics, Line, Tlen+1, 34, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 73, C =< 75 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 77, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 103 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 105, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(67, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,67};
yystate(66, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(66, [78|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 34, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 77 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 79, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(66, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,66};
yystate(65, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 3, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 3, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 3, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 3, Tlen);
yystate(65, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,65};
yystate(64, [117|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 11, Tlen);
yystate(64, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 11, Tlen);
yystate(64, [62|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 11, Tlen);
yystate(64, [61|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 11, Tlen);
yystate(64, [60|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 11, Tlen);
yystate(64, [45|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 11, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 11, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 11, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(93, Ics, Line, Tlen+1, 11, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 11, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,64};
yystate(63, [104|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(63, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(63, [72|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(63, [71|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(63, Ics, Line, Tlen+1, 34, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(63, Ics, Line, Tlen+1, 34, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 73, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 103 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 105, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(63, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,63};
yystate(62, [114|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 34, Tlen);
yystate(62, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(62, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,62};
yystate(61, [105|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 34, Tlen);
yystate(61, [97|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 34, Tlen);
yystate(61, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 104 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(61, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,61};
yystate(60, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(60, [60|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 34, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(60, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,60};
yystate(59, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 8, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 8, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 8, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 8, Tlen);
yystate(59, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,59};
yystate(58, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 15, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 15, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 15, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 15, Tlen);
yystate(58, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line,58};
yystate(57, [116|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 34, Tlen);
yystate(57, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(57, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,57};
yystate(56, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(56, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,56};
yystate(55, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(55, [76|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 34, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 75 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 77, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(55, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,55};
yystate(54, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(54, [78|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 34, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 77 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 79, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(54, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,54};
yystate(53, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 4, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 4, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 4, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 4, Tlen);
yystate(53, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,53};
yystate(52, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line};
yystate(51, [104|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(51, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(51, [76|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 34, Tlen);
yystate(51, [72|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(51, [71|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(63, Ics, Line, Tlen+1, 34, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(63, Ics, Line, Tlen+1, 34, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 73, C =< 75 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 77, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 103 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 105, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,51};
yystate(50, [114|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 34, Tlen);
yystate(50, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,50};
yystate(49, [98|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 34, Tlen);
yystate(49, [97|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(49, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 99, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,49};
yystate(48, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(48, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,48};
yystate(47, [104|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(47, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(47, [72|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(47, [71|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(47, [65|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 34, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(63, Ics, Line, Tlen+1, 34, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 66, C =< 70 ->
    yystate(63, Ics, Line, Tlen+1, 34, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 73, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 103 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 105, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(47, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,47};
yystate(46, [111|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 34, Tlen);
yystate(46, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,46};
yystate(45, [101|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 34, Tlen);
yystate(45, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(45, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,45};
yystate(44, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(44, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,44};
yystate(43, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 6, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 6, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 6, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 6, Tlen);
yystate(43, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,43};
yystate(42, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(41, [108|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 34, Tlen);
yystate(41, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(41, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,41};
yystate(40, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line};
yystate(39, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(39, [80|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 34, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 79 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 81, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(39, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,39};
yystate(38, [78|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(38, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,38};
yystate(37, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 5, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 5, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 5, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 5, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,37};
yystate(36, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(36, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,36};
yystate(35, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 7, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 7, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 7, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 7, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,35};
yystate(34, [124|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 10, Tlen);
yystate(34, [121|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 10, Tlen);
yystate(34, [122|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 10, Tlen);
yystate(34, [120|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 10, Tlen);
yystate(34, [111|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 10, Tlen);
yystate(34, [97|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 10, Tlen);
yystate(34, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 10, Tlen);
yystate(34, [94|Ics], Line, Tlen, _, _) ->
    yystate(90, Ics, Line, Tlen+1, 10, Tlen);
yystate(34, [45|Ics], Line, Tlen, _, _) ->
    yystate(98, Ics, Line, Tlen+1, 10, Tlen);
yystate(34, [43|Ics], Line, Tlen, _, _) ->
    yystate(108, Ics, Line, Tlen+1, 10, Tlen);
yystate(34, [38|Ics], Line, Tlen, _, _) ->
    yystate(100, Ics, Line, Tlen+1, 10, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 10, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 10, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 110 ->
    yystate(93, Ics, Line, Tlen+1, 10, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 119 ->
    yystate(93, Ics, Line, Tlen+1, 10, Tlen);
yystate(34, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,34};
yystate(33, [122|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 34, Tlen);
yystate(33, [109|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 34, Tlen);
yystate(33, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 121 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,33};
yystate(32, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(32, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,32};
yystate(31, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(31, [90|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 34, Tlen);
yystate(31, [77|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 34, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 76 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 78, C =< 89 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(31, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,31};
yystate(30, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line};
yystate(29, [112|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 34, Tlen);
yystate(29, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 111 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 113, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(29, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,29};
yystate(28, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line};
yystate(27, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(27, [76|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 34, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 75 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 77, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(27, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,27};
yystate(26, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(26, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,26};
yystate(25, [115|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 34, Tlen);
yystate(25, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(25, [45|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 34, Tlen);
yystate(25, [43|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 34, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,25};
yystate(24, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(24, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(24, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,24};
yystate(23, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(23, [69|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 34, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 70, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(23, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,23};
yystate(22, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(22, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,22};
yystate(21, [112|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 34, Tlen);
yystate(21, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 111 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 113, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,21};
yystate(20, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line};
yystate(19, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(19, [66|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 34, Tlen);
yystate(19, [65|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 67, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,19};
yystate(18, [117|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 34, Tlen);
yystate(18, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(18, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,18};
yystate(17, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 24, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 24, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 24, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 24, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line,17};
yystate(16, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(16, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,16};
yystate(15, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(15, [84|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 34, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 83 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 85, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(15, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,15};
yystate(14, [108|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 34, Tlen);
yystate(14, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(14, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,14};
yystate(13, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(13, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,13};
yystate(12, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line};
yystate(11, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(11, [73|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 34, Tlen);
yystate(11, [65|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 34, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 66, C =< 72 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 74, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,11};
yystate(10, [108|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 34, Tlen);
yystate(10, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(10, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,10};
yystate(9, Ics, Line, Tlen, _, _) ->
    {31,Tlen,Ics,Line};
yystate(8, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(8, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,8};
yystate(7, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line};
yystate(6, [108|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 34, Tlen);
yystate(6, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(6, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,6};
yystate(5, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(5, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,5};
yystate(4, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(4, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,4};
yystate(3, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(3, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,3};
yystate(2, [97|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 34, Tlen);
yystate(2, [95|Ics], Line, Tlen, _, _) ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(93, Ics, Line, Tlen+1, 34, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,2};
yystate(1, Ics, Line, Tlen, _, _) ->
    {30,Tlen,Ics,Line};
yystate(0, [84|Ics], Line, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Tlen+1, Action, Alen);
yystate(0, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine);
yyaction(1, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine);
yyaction(2, _, _, _) ->
    yyaction_2();
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine);
yyaction(5, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine);
yyaction(6, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars, TokenLine);
yyaction(7, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars, TokenLine);
yyaction(8, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars, TokenLine);
yyaction(9, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars, TokenLine);
yyaction(10, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars, TokenLine);
yyaction(11, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars, TokenLine);
yyaction(12, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars, TokenLine);
yyaction(13, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars, TokenLine);
yyaction(14, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars, TokenLine);
yyaction(15, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars, TokenLine);
yyaction(16, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_16(TokenChars, TokenLine);
yyaction(17, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_17(TokenChars, TokenLine);
yyaction(18, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_18(TokenChars, TokenLine);
yyaction(19, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_19(TokenChars, TokenLine);
yyaction(20, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_20(TokenChars, TokenLine);
yyaction(21, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_21(TokenChars, TokenLine);
yyaction(22, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_22(TokenChars, TokenLine);
yyaction(23, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_23(TokenChars, TokenLine);
yyaction(24, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_24(TokenChars, TokenLine);
yyaction(25, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_25(TokenChars, TokenLine);
yyaction(26, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_26(TokenChars, TokenLine);
yyaction(27, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_27(TokenChars, TokenLine);
yyaction(28, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_28(TokenChars, TokenLine);
yyaction(29, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_29(TokenChars, TokenLine);
yyaction(30, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_30(TokenChars, TokenLine);
yyaction(31, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_31(TokenChars, TokenLine);
yyaction(32, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_32(TokenChars, TokenLine);
yyaction(33, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_33(TokenChars, TokenLine);
yyaction(34, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_34(TokenChars, TokenLine);
yyaction(35, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_35(TokenChars, TokenLine);
yyaction(36, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_36(TokenChars, TokenLine);
yyaction(37, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_37(TokenChars, TokenLine);
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/2}).
-file("./priv/asm_lexer.xrl", 88).
yyaction_0(TokenChars, TokenLine) ->
     { token, { t_comment, TokenLine, str_validate (TokenChars, TokenLine) } } .

-compile({inline,yyaction_1/2}).
-file("./priv/asm_lexer.xrl", 90).
yyaction_1(TokenChars, TokenLine) ->
     { token, { t_next_str, TokenLine, TokenChars } } .

-compile({inline,yyaction_2/0}).
-file("./priv/asm_lexer.xrl", 91).
yyaction_2() ->
     skip_token .

-compile({inline,yyaction_3/2}).
-file("./priv/asm_lexer.xrl", 92).
yyaction_3(TokenChars, TokenLine) ->
     { token, { t_org, TokenLine, TokenChars } } .

-compile({inline,yyaction_4/2}).
-file("./priv/asm_lexer.xrl", 93).
yyaction_4(TokenChars, TokenLine) ->
     { token, { t_lit, TokenLine, TokenChars } } .

-compile({inline,yyaction_5/2}).
-file("./priv/asm_lexer.xrl", 94).
yyaction_5(TokenChars, TokenLine) ->
     { token, { t_label, TokenLine, TokenChars } } .

-compile({inline,yyaction_6/2}).
-file("./priv/asm_lexer.xrl", 95).
yyaction_6(TokenChars, TokenLine) ->
     { token, { t_jmp, TokenLine, TokenChars } } .

-compile({inline,yyaction_7/2}).
-file("./priv/asm_lexer.xrl", 96).
yyaction_7(TokenChars, TokenLine) ->
     { token, { t_jz, TokenLine, TokenChars } } .

-compile({inline,yyaction_8/2}).
-file("./priv/asm_lexer.xrl", 97).
yyaction_8(TokenChars, TokenLine) ->
     { token, { t_call, TokenLine, TokenChars } } .

-compile({inline,yyaction_9/2}).
-file("./priv/asm_lexer.xrl", 98).
yyaction_9(TokenChars, TokenLine) ->
     { token, { t_alu, TokenLine, TokenChars } } .

-compile({inline,yyaction_10/2}).
-file("./priv/asm_lexer.xrl", 100).
yyaction_10(TokenChars, TokenLine) ->
     { token, { opcode_00, TokenLine, TokenChars } } .

-compile({inline,yyaction_11/2}).
-file("./priv/asm_lexer.xrl", 101).
yyaction_11(TokenChars, TokenLine) ->
     { token, { opcode_01, TokenLine, TokenChars } } .

-compile({inline,yyaction_12/2}).
-file("./priv/asm_lexer.xrl", 102).
yyaction_12(TokenChars, TokenLine) ->
     { token, { opcode_02, TokenLine, TokenChars } } .

-compile({inline,yyaction_13/2}).
-file("./priv/asm_lexer.xrl", 103).
yyaction_13(TokenChars, TokenLine) ->
     { token, { opcode_03, TokenLine, TokenChars } } .

-compile({inline,yyaction_14/2}).
-file("./priv/asm_lexer.xrl", 104).
yyaction_14(TokenChars, TokenLine) ->
     { token, { opcode_04, TokenLine, TokenChars } } .

-compile({inline,yyaction_15/2}).
-file("./priv/asm_lexer.xrl", 105).
yyaction_15(TokenChars, TokenLine) ->
     { token, { opcode_05, TokenLine, TokenChars } } .

-compile({inline,yyaction_16/2}).
-file("./priv/asm_lexer.xrl", 106).
yyaction_16(TokenChars, TokenLine) ->
     { token, { opcode_06, TokenLine, TokenChars } } .

-compile({inline,yyaction_17/2}).
-file("./priv/asm_lexer.xrl", 107).
yyaction_17(TokenChars, TokenLine) ->
     { token, { opcode_07, TokenLine, TokenChars } } .

-compile({inline,yyaction_18/2}).
-file("./priv/asm_lexer.xrl", 108).
yyaction_18(TokenChars, TokenLine) ->
     { token, { opcode_08, TokenLine, TokenChars } } .

-compile({inline,yyaction_19/2}).
-file("./priv/asm_lexer.xrl", 109).
yyaction_19(TokenChars, TokenLine) ->
     { token, { opcode_09, TokenLine, TokenChars } } .

-compile({inline,yyaction_20/2}).
-file("./priv/asm_lexer.xrl", 110).
yyaction_20(TokenChars, TokenLine) ->
     { token, { opcode_10, TokenLine, TokenChars } } .

-compile({inline,yyaction_21/2}).
-file("./priv/asm_lexer.xrl", 111).
yyaction_21(TokenChars, TokenLine) ->
     { token, { opcode_11, TokenLine, TokenChars } } .

-compile({inline,yyaction_22/2}).
-file("./priv/asm_lexer.xrl", 112).
yyaction_22(TokenChars, TokenLine) ->
     { token, { opcode_12, TokenLine, TokenChars } } .

-compile({inline,yyaction_23/2}).
-file("./priv/asm_lexer.xrl", 113).
yyaction_23(TokenChars, TokenLine) ->
     { token, { opcode_13, TokenLine, TokenChars } } .

-compile({inline,yyaction_24/2}).
-file("./priv/asm_lexer.xrl", 114).
yyaction_24(TokenChars, TokenLine) ->
     { token, { opcode_14, TokenLine, TokenChars } } .

-compile({inline,yyaction_25/2}).
-file("./priv/asm_lexer.xrl", 115).
yyaction_25(TokenChars, TokenLine) ->
     { token, { opcode_15, TokenLine, TokenChars } } .

-compile({inline,yyaction_26/2}).
-file("./priv/asm_lexer.xrl", 117).
yyaction_26(TokenChars, TokenLine) ->
     { token, { flag_12, TokenLine, TokenChars } } .

-compile({inline,yyaction_27/2}).
-file("./priv/asm_lexer.xrl", 118).
yyaction_27(TokenChars, TokenLine) ->
     { token, { flag_7, TokenLine, TokenChars } } .

-compile({inline,yyaction_28/2}).
-file("./priv/asm_lexer.xrl", 119).
yyaction_28(TokenChars, TokenLine) ->
     { token, { flag_6, TokenLine, TokenChars } } .

-compile({inline,yyaction_29/2}).
-file("./priv/asm_lexer.xrl", 120).
yyaction_29(TokenChars, TokenLine) ->
     { token, { flag_5, TokenLine, TokenChars } } .

-compile({inline,yyaction_30/2}).
-file("./priv/asm_lexer.xrl", 122).
yyaction_30(TokenChars, TokenLine) ->
     { token, { flag_d_plus, TokenLine, TokenChars } } .

-compile({inline,yyaction_31/2}).
-file("./priv/asm_lexer.xrl", 123).
yyaction_31(TokenChars, TokenLine) ->
     { token, { flag_d_minus, TokenLine, TokenChars } } .

-compile({inline,yyaction_32/2}).
-file("./priv/asm_lexer.xrl", 124).
yyaction_32(TokenChars, TokenLine) ->
     { token, { flag_r_plus, TokenLine, TokenChars } } .

-compile({inline,yyaction_33/2}).
-file("./priv/asm_lexer.xrl", 125).
yyaction_33(TokenChars, TokenLine) ->
     { token, { flag_r_minus, TokenLine, TokenChars } } .

-compile({inline,yyaction_34/2}).
-file("./priv/asm_lexer.xrl", 129).
yyaction_34(TokenChars, TokenLine) ->
     { token, { ident, TokenLine, id_validate (TokenChars, TokenLine) } } .

-compile({inline,yyaction_35/2}).
-file("./priv/asm_lexer.xrl", 130).
yyaction_35(TokenChars, TokenLine) ->
     { token, { integer, TokenLine, int_validate (TokenChars, TokenLine) } } .

-compile({inline,yyaction_36/2}).
-file("./priv/asm_lexer.xrl", 131).
yyaction_36(TokenChars, TokenLine) ->
     { token, { integer, TokenLine, intwr_validate (TokenChars, TokenLine) } } .

-compile({inline,yyaction_37/2}).
-file("./priv/asm_lexer.xrl", 132).
yyaction_37(TokenChars, TokenLine) ->
     { token, { string, TokenLine, str_validate (TokenChars, TokenLine) } } .

-file("/usr/local/Cellar/erlang/23.3.1/lib/erlang/lib/parsetools-2.2/include/leexinc.hrl", 313).
